name: PrimGrp
version: 3.4.2
date: 2022-05-03
description: |
    GAP Primitive Permutation Groups Library

authors:
    - name: Alexander Hulpke
      url: http://www.math.colostate.edu/~hulpke
    - name: Colva M. Roney-Dougal
      url: http://www-groups.mcs.st-and.ac.uk/~colva/
    - name: Christopher Russell
      url: mailto:cr66@st-andrews.ac.uk

maintainers:
    - name: Alexander Hulpke
      url: http://www.math.colostate.edu/~hulpke
    - name: Olexandr Konovalov
      url: https://alex-konovalov.github.io/
    - name: Christopher Russell
      url: mailto:cr66@st-andrews.ac.uk

GAP: "4.10.0"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/primgrp/
readme: README.md
packageinfo: https://gap-packages.github.io/primgrp/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/primgrp/releases/download/v3.4.2/primgrp-3.4.2.tar.gz

abstract: |
    The <span class="pkgname">PrimGrp</span> package provides the library   of primitive permutation groups which includes, up to permutation isomorphism   (i.e., up to conjugacy in the corresponding symmetric group), all primitive   permutation groups of degree &lt; 4096.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
