name: PrimGrp
version: "4.0.1"
license: "GPL-2.0-or-later"
date: 2025-09-24
description: |
    GAP Primitive Permutation Groups Library

authors:
    - name: Alexander Hulpke
      url: https://www.math.colostate.edu/~hulpke/
    - name: Jesse Lansdown
      url: https://www.jesselansdown.com
    - name: Colva M. Roney-Dougal
      url: http://www-groups.mcs.st-and.ac.uk/~colva/
    - name: Christopher Russell
      url: mailto:chriswgrussell@hotmail.co.uk

maintainers:
    - name: Alexander Hulpke
      url: https://www.math.colostate.edu/~hulpke/
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/
    - name: Jesse Lansdown
      url: https://www.jesselansdown.com

GAP: "4.10.0"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/primgrp/
readme: README.md
packageinfo: https://gap-packages.github.io/primgrp/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/primgrp/releases/download/v4.0.1/primgrp-4.0.1.tar.gz

abstract: |
    The <span class="pkgname">PrimGrp</span> package provides the library   of primitive permutation groups which includes, up to permutation isomorphism   (i.e., up to conjugacy in the corresponding symmetric group), all primitive   permutation groups of degree &lt; 8192.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    primitive permutation group.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HKLRR25</span>]   <b class='BibAuthor'>Hulpke, A., Konovalov, O., Lansdown, J., Roney-Dougal, C. M. and Russell, C.</b>,
     <i class='BibTitle'>PrimGrp, GAP Primitive Permutation Groups Library,
             Version 4.0.1</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/primgrp/">https://gap-packages.github.io/primgrp/</a></span>.
    </p>
    

bibtex: |
    @misc{ PrimGrp,
      author =           {Hulpke,  A.  and  Konovalov,  O.  and Lansdown, J. and
                          Roney\texttt{\symbol{45}}Dougal, C. M. and Russell, C.},
      title =            {{PrimGrp}, {GAP Primitive Permutation Groups Library},
                          {V}ersion 4.0.1},
      month =            {Sep},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href        {https://gap-packages.github.io/primgrp/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{primgrp/}}},
      keywords =         {primitive permutation group},
      printedkey =       {HKLRR25}
    }

