name: PrimGrp
version: "3.4.4"
license: "GPL-2.0-or-later"
date: 2023-02-25
description: |
    GAP Primitive Permutation Groups Library

authors:
    - name: Alexander Hulpke
      url: https://www.math.colostate.edu/~hulpke/
    - name: Colva M. Roney-Dougal
      url: http://www-groups.mcs.st-and.ac.uk/~colva/
    - name: Christopher Russell
      url: mailto:cr66@st-andrews.ac.uk

maintainers:
    - name: Alexander Hulpke
      url: https://www.math.colostate.edu/~hulpke/
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/
    - name: Christopher Russell
      url: mailto:cr66@st-andrews.ac.uk

GAP: "4.10.0"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/primgrp/
readme: README.md
packageinfo: https://gap-packages.github.io/primgrp/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/primgrp/releases/download/v3.4.4/primgrp-3.4.4.tar.gz

abstract: |
    The <span class="pkgname">PrimGrp</span> package provides the library   of primitive permutation groups which includes, up to permutation isomorphism   (i.e., up to conjugacy in the corresponding symmetric group), all primitive   permutation groups of degree &lt; 4096.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    primitive permutation group.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HKRR23</span>]   <b class='BibAuthor'>Hulpke, A., Konovalov, O., Roney-Dougal, C. M. and Russell, C.</b>,
     <i class='BibTitle'>PrimGrp, GAP Primitive Permutation Groups Library,
             Version 3.4.4</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/primgrp/">https://gap-packages.github.io/primgrp/</a></span>.
    </p>
    

bibtex: |
    @misc{ PrimGrp3.4.4,
      author =           {Hulpke, A. and Konovalov, O. and Roney\texttt{\symbol{45}}Dougal, C. M. and Russell, C.},
      title =            {{PrimGrp}, GAP Primitive Permutation Groups Library, {V}ersion 3.4.4},
      month =            {Feb},
      year =             {2023},
      note =             {GAP package},
      howpublished =     {\href                                             {https://gap-packages.github.io/primgrp/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{primgrp/}}},
      keywords =         {primitive permutation group},
      printedkey =       {HKRR23}
    }

