#!/usr/bin/env python3
"""Move Sims' numbering out of the entries and into a table of its own.

Every entry of degree at most 50 carries a tenth field, Sims' number for that
group.  It is real data -- most of those numbers are not the entry's own -- but
406 values do not justify a column on the main table, and while an entry ends
in ",1" it cannot be written as a call: PGAlt(14,1) and [...,"Alt",1] are not
the same text.  So this has to happen before any generic constructor can be
used.

Rewrites data/gps*.g to drop the tenth field and writes the values into
lib/primitiv.grp as PRIMGRP_SIMSNO, between the two markers there.

The entries are not one to a line -- a degree's list wraps across lines and its
entries are indented into it -- so this walks brackets over the whole file
rather than reading lines, and excises the field's own span, leaving the rest
of the text as it was.

Nothing is written until every file has been read and the table checked, so a
run that stops on a bad table leaves the tree untouched.

Usage: move-simsno.py <datadir> <grpfile>
"""
import sys, os, glob, re

BEGIN = "##  <<< PRIMGRP_SIMSNO, generated by dev/move-simsno.py >>>\n"
END = "##  <<< end PRIMGRP_SIMSNO >>>\n"


def scan_top(s, start):
    """(begin, end) of each top-level [...] inside the list opening at start"""
    assert s[start] == '['
    i, depth, quoted, begin = start + 1, 0, False, None
    while i < len(s):
        ch = s[i]
        if quoted:
            if ch == '\\':
                i += 2
                continue
            if ch == '"':
                quoted = False
        elif ch == '"':
            quoted = True
        elif ch == '[':
            if depth == 0:
                begin = i
            depth += 1
        elif ch == ']':
            depth -= 1
            if depth == 0:
                yield (begin, i + 1)
            elif depth < 0:
                return
        i += 1


def fields(entry):
    """(begin, end) of each top-level field inside an entry's brackets"""
    out, i, depth, quoted, begin = [], 1, 0, False, 1
    while i < len(entry) - 1:
        ch = entry[i]
        if quoted:
            if ch == '\\':
                i += 2
                continue
            if ch == '"':
                quoted = False
        elif ch == '"':
            quoted = True
        elif ch in '[(':
            depth += 1
        elif ch in '])':
            depth -= 1
        elif ch == ',' and depth == 0:
            out.append((begin, i))
            begin = i + 1
        i += 1
    out.append((begin, len(entry) - 1))
    return out


def main(argv):
    if len(argv) != 2:
        sys.exit(__doc__)
    datadir, grpfile = argv

    sims, edits = {}, {}
    for path in sorted(glob.glob(os.path.join(datadir, 'gps*.g'))):
        s = open(path).read()
        cuts = []
        for m in re.finditer(r'^PRIMGRP\[(\d+)\]:=\s*', s, re.M):
            deg = int(m.group(1))
            lb = s.index('[', m.end() - 1)
            for (b, e) in scan_top(s, lb):
                fs = fields(s[b:e])
                if len(fs) == 10:
                    nr = int(s[b + fs[0][0]:b + fs[0][1]].strip())
                    sims.setdefault(deg, {})[nr] = \
                        s[b + fs[9][0]:b + fs[9][1]].strip()
                    # from the comma before the tenth field to the end of
                    # its digits, leaving whatever spacing followed it so the
                    # diff is the removal and nothing else
                    stop = b + fs[9][0] + len(
                        s[b + fs[9][0]:b + fs[9][1]].rstrip())
                    cuts.append((b + fs[8][1], stop))
                elif deg <= 50:
                    sys.exit(f"ABORT: degree {deg} entry has {len(fs)} fields,"
                             " not ten; has this already been run?")
        if cuts:
            out, last = [], 0
            for (a, z) in cuts:
                out.append(s[last:a])
                last = z
            out.append(s[last:])
            edits[path] = ''.join(out)

    if not sims:
        sys.exit("ABORT: no ten-field entries found, nothing to move")

    degrees = sorted(sims)
    total = sum(len(v) for v in sims.values())
    differ = sum(1 for d in sims for nr, v in sims[d].items() if v != str(nr))
    if degrees[0] != 2:
        sys.exit(f"ABORT: the lowest degree with a tenth field is {degrees[0]},"
                 " but PRIMGRP_SIMSNO[deg-1] is positional from 2")
    if degrees != list(range(2, degrees[-1] + 1)):
        missing = sorted(set(range(2, degrees[-1] + 1)) - set(degrees))
        sys.exit(f"ABORT: degrees {missing[:5]} carry no tenth field but "
                 f"{degrees[-1]} does; the table would be ragged")
    for d in degrees:
        got = sorted(sims[d])
        if got != list(range(1, len(got) + 1)):
            sys.exit(f"ABORT: degree {d} has entry numbers {got[:5]}...,"
                     " not 1 upwards")

    rows = ["[" + ",".join(sims[d][n] for n in sorted(sims[d])) + "]"
            for d in degrees]
    body = (BEGIN +
            "#####################################################"
            "########################\n##\n#V  PRIMGRP_SIMSNO\n##\n"
            f"##  Sims' numbering of the primitive groups of degree at most "
            f"{degrees[-1]}.  It\n"
            "##  orders the same groups differently, so PRIMGRP_SIMSNO[deg-1]"
            "[nr] is Sims'\n"
            "##  number for PrimitiveGroup(deg,nr), and it is not the identity"
            f": {differ} of\n##  these {total} numbers differ from nr.  Small "
            "enough to keep here rather\n##  than as a tenth field on every "
            "entry of PRIMGRP.\n##\n"
            'BindGlobal("PRIMGRP_SIMSNO", [\n' +
            ",\n".join(rows) + "]);\n\n" + END)

    grp = open(grpfile).read()
    if BEGIN not in grp or END not in grp:
        sys.exit(f"ABORT: markers missing from {grpfile}")

    for path, text in edits.items():
        open(path, 'w').write(text)
    open(grpfile, 'w').write(
        grp[:grp.index(BEGIN)] + body + grp[grp.index(END) + len(END):])

    print(f"{total} Sims numbers over degrees 2 to {degrees[-1]}, "
          f"{differ} of them different from the entry's own number; "
          f"{len(edits)} data file(s) rewritten")


main(sys.argv[1:])
